services:
  - type: web
    name: flask-app
    env: python
    region: oregon   # puedes cambiarlo según donde quieras desplegar
    plan: free       # o starter/standard si necesitas más recursos
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 4 --threads 2 --bind 0.0.0.0:10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
